# Generated by Django 5.2 on 2026-02-05 09:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employerprofile',
            old_name='slogan',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='company_address',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='employee_count',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='founded_year',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='ratings',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='review_count',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='website',
        ),
        migrations.AddField(
            model_name='company',
            name='company_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='custom_id',
            field=models.CharField(blank=True, help_text='Custom ID like CMP-001, STA001 (auto-generated if empty)', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='company',
            name='employee_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='founded_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Admin can disable company'),
        ),
        migrations.AddField(
            model_name='company',
            name='slogan',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employers', to='jobapp.company'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this job is currently active and visible'),
        ),
        migrations.AlterField(
            model_name='job',
            name='posted_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
