# Generated by Django 5.2 on 2026-02-06 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_rename_slogan_employerprofile_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerprofile',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
