# Generated by Django 5.2 on 2026-02-08 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0003_alter_employerprofile_employee_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='description',
            new_name='company_overview',
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='job',
            name='job_highlights',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('resume_screening', 'Resume Screening'), ('recruiter_review', 'Recruiter Review'), ('shortlisted', 'Shortlisted'), ('interview_called', 'Interview Called'), ('offered', 'Offered'), ('rejected', 'Rejected'), ('hired', 'Hired'), ('withdrawn', 'Withdrawn')], default='applied', max_length=30),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['user', 'job'], name='jobapp_joba_user_id_e280ea_idx'),
        ),
    ]
