# Generated by Django 5.2 on 2026-02-10 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0005_alter_jobseekerprofile_current_ctc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(default='Job Seeker', max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('show_online_status', models.BooleanField(default=True)),
                ('show_read_receipts', models.BooleanField(default=True)),
                ('restrict_duplicate_applications', models.BooleanField(default=False)),
                ('hide_cv', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
