# Generated by Django 5.2 on 2026-02-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0006_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Open', 'Open'), ('Hiring in Progress', 'Hiring in Progress'), ('On Hold', 'On Hold'), ('Filled', 'Filled'), ('Closed', 'Closed')], default='Draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience_required',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
