# Generated by Django 5.2 on 2026-06-09 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0008_alter_plan_options_plan_account_manager_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adminaccesslog',
            table='AdminAccessLog',
        ),
        migrations.AlterModelTable(
            name='adminquiethours',
            table='AdminQuietHours',
        ),
        migrations.AlterModelTable(
            name='admintrusteddevice',
            table='AdminTrustedDevice',
        ),
        migrations.AlterModelTable(
            name='applicationflag',
            table='ApplicationFlag',
        ),
        migrations.AlterModelTable(
            name='companyreview',
            table='CompanyReview',
        ),
        migrations.AlterModelTable(
            name='employerplatformsettings',
            table='EmployerPlatformSettings',
        ),
        migrations.AlterModelTable(
            name='jobseekerplatformsettings',
            table='JobseekerPlatformSettings',
        ),
        migrations.AlterModelTable(
            name='notificationchannelsettings',
            table='NotificationChannelSettings',
        ),
        migrations.AlterModelTable(
            name='notificationconfig',
            table='NotificationConfig',
        ),
        migrations.AlterModelTable(
            name='notificationdeliverylog',
            table='NotificationDeliveryLog',
        ),
        migrations.AlterModelTable(
            name='passwordresettoken',
            table='PasswordResetToken',
        ),
        migrations.AlterModelTable(
            name='planfeature',
            table='PlanFeature',
        ),
        migrations.AlterModelTable(
            name='smsotp',
            table='SMSOTP',
        ),
        migrations.AlterModelTable(
            name='userdevice',
            table='UserDevice',
        ),
    ]
