# Generated by Django 5.2 on 2026-06-10 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0009_alter_adminaccesslog_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Blog Categories',
                'db_table': 'BlogCategory',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('heading', models.CharField(blank=True, default='', max_length=500)),
                ('desc', models.TextField(blank=True, default='')),
                ('thumbnail', models.ImageField(blank=True, default='', null=True, upload_to='blog_thumbnails/')),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft')], default='Draft', max_length=20)),
                ('date', models.CharField(blank=True, default='', max_length=50)),
                ('time', models.CharField(blank=True, default='12:00 PM', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='jobapp.blogcategory')),
            ],
            options={
                'db_table': 'Blog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='jobapp.blog')),
            ],
            options={
                'db_table': 'BlogPoint',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PointContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='jobapp.blogpoint')),
            ],
            options={
                'db_table': 'PointContent',
                'ordering': ['order'],
            },
        ),
    ]
