# Generated by Django 5.2 on 2026-06-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0010_blogcategory_blog_blogpoint_pointcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerRegistrationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_registration', models.BooleanField(default=True)),
                ('email_verification', models.BooleanField(default=True)),
                ('mobile_verification', models.BooleanField(default=False)),
                ('approval_type', models.CharField(choices=[('Manual Type', 'Manual Type'), ('Automatic', 'Automatic')], default='Manual Type', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='employerplatformsettings',
            name='approval_type',
        ),
        migrations.RemoveField(
            model_name='employerplatformsettings',
            name='email_verification',
        ),
        migrations.RemoveField(
            model_name='employerplatformsettings',
            name='employer_registration',
        ),
        migrations.RemoveField(
            model_name='employerplatformsettings',
            name='mobile_verification',
        ),
    ]
