# Generated by Django 5.2 on 2026-06-16 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0011_employerregistrationsettings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationdeliverylog',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='jobapp.notification'),
        ),
    ]
