# Generated by Django 5.2 on 2026-06-17 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0012_alter_notificationdeliverylog_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('department', models.CharField(choices=[('support', 'Support'), ('sales', 'Sales'), ('billing', 'Billing'), ('technical', 'Technical'), ('general', 'General')], default='general', max_length=20)),
                ('title', models.CharField(default='Account Manager', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='account_managers/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_account_managers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'AccountManager',
                'ordering': ['order', 'department'],
            },
        ),
        migrations.CreateModel(
            name='EmployerAccountManagerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_employers', to='jobapp.accountmanager')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_manager_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'EmployerAccountManagerAssignment',
                'unique_together': {('employer', 'account_manager')},
            },
        ),
    ]
