# Generated by Django 5.2 on 2026-06-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0013_accountmanager_employeraccountmanagerassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='sms_verified',
            field=models.BooleanField(default=False),
        ),
    ]
