# Generated by Django 5.2 on 2026-06-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0014_adminprofile_email_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdevice',
            name='fcm_token',
            field=models.TextField(),
        ),
    ]
