# Generated by Django 5.2 on 2026-07-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0015_alter_userdevice_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='resolved_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Contacted', 'Contacted'), ('Resolved', 'Resolved')], default='Pending', max_length=20),
        ),
    ]
