# Generated by Django 5.2 on 2026-07-02 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0016_contactmessage_resolved_on_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employerregistrationsettings',
            table='EmployerRegistrationSettings',
        ),
    ]
