# Generated by Django 5.2 on 2026-07-07 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0017_alter_employerregistrationsettings_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='reported_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='jobapp.postajob'),
        ),
    ]
