# Generated by Django 5.2 on 2026-07-07 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0018_alter_complaint_reported_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='original_job_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='Stores the job ID even if the job is deleted', null=True),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['original_job_id'], name='Complaint_origina_1b3ebb_idx'),
        ),
    ]
