# Generated by Django 5.2 on 2026-07-10 11:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0019_complaint_original_job_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerWeeklyReportToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_report_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'EmployerWeeklyReportToken',
            },
        ),
    ]
