# Generated by Django 5.2 on 2026-07-11 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0020_employerweeklyreporttoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postajob',
            name='job_status',
            field=models.CharField(choices=[('Hiring in Progress', 'Hiring in Progress'), ('Reviewing Application', 'Reviewing Application'), ('Hiring Done', 'Hiring Done')], default='Hiring in Progress', max_length=50),
        ),
    ]
