# Generated by Django 5.2 on 2026-04-08 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0023_alter_employerprofile_company_and_more'),
    ]

    operations = [
    ]
