# Generated by Django 5.2 on 2026-04-08 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0024_fix_json_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='languageknown',
            options={},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='languageknown',
            name='unique_language_per_profile',
        ),
        migrations.RemoveConstraint(
            model_name='skill',
            name='unique_skill_per_profile',
        ),
        migrations.AlterUniqueTogether(
            name='languageknown',
            unique_together={('profile', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together={('profile', 'name')},
        ),
    ]
