# Generated by Django 5.2 on 2026-08-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0025_chatsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='intro_video',
            field=models.FileField(blank=True, null=True, upload_to='intro_videos/'),
        ),
    ]
