# Generated by Django 5.2 on 2026-04-13 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0026_locationmaster_pendinglocationrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LocationMaster',
        ),
        migrations.DeleteModel(
            name='PendingLocationRequest',
        ),
    ]
