# Generated by Django 5.2 on 2026-04-16 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0027_delete_locationmaster_delete_pendinglocationrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='companyverification',
            name='registration_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='companyverification',
            name='tax_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='companyverification',
            unique_together={('employer', 'legal_name')},
        ),
    ]
