# Generated by Django 5.2 on 2026-08-18 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0027_pendingnotification'),
        ('jobapp', '0028_backfill_message_notification_conversation_id'),
    ]

    operations = [
    ]
