# Generated by Django 5.2 on 2026-04-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0029_companyemailotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='price',
        ),
        migrations.AddField(
            model_name='invoice',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='expiry_date',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='subscription',
            name='duration',
            field=models.CharField(default='monthly', max_length=20),
        ),
    ]
