# Generated by Django 5.2 on 2026-08-18 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0030_subscription_payment_jobseekersecurityprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyverification',
            name='registration_certificate',
            field=models.FileField(blank=True, null=True, upload_to='company/registration/'),
        ),
        migrations.AddField(
            model_name='companyverification',
            name='tax_certificate',
            field=models.FileField(blank=True, null=True, upload_to='company/tax/'),
        ),
    ]
