# Generated by Django 5.2 on 2026-04-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0030_remove_plan_price_invoice_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('Fresher', 'Fresher'), ('Experienced', 'Experienced')], max_length=20, null=True),
        ),
    ]
