# Generated by Django 6.0.2 on 2026-04-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0030_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='postajob',
            name='last_date_to_apply',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyverification',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Hold', 'Hold'), ('Reject', 'Reject'), ('Verified', 'Verified')], db_index=True, default='pending', max_length=10),
        ),
    ]
