# Generated by Django 5.2 on 2026-08-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0031_companyverification_registration_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyverification',
            name='incorporation_certificate',
            field=models.FileField(blank=True, null=True, upload_to='company_certificates/'),
        ),
    ]
