# Generated by Django 6.0.2 on 2026-04-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0031_postajob_last_date_to_apply_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employer',
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Hold', 'Hold'), ('Deactivated', 'Deactivated')], default='Active', max_length=15),
        ),
    ]
