# Generated by Django 6.0.2 on 2026-05-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0032_delete_employer_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
