# Generated by Django 5.2 on 2026-08-19 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0032_alter_companyverification_incorporation_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='company_type',
            field=models.CharField(choices=[('main', 'Main company'), ('partner', 'Partner / consultancy company')], default='main', max_length=10),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='parent_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_companies', to='jobapp.companyprofile'),
        ),
        migrations.AddField(
            model_name='companyverification',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to='jobapp.companyprofile'),
        ),
    ]
