# Generated by Django 5.2 on 2026-08-21 10:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0032_alter_companyverification_incorporation_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='tagline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='CompanyAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='announcements/')),
                ('announcement_type', models.CharField(choices=[('general', 'General'), ('hiring', 'Hiring'), ('event', 'Event'), ('deadline', 'Deadline'), ('notice', 'Notice')], default='general', max_length=30)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('expired', 'Expired')], default='published', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='jobapp.companyprofile')),
            ],
            options={
                'db_table': 'CompanyAnnouncement',
                'ordering': ['-created_at'],
            },
        ),
    ]
