# Generated by Django 5.2 on 2026-05-04 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0031_jobseekerprofile_employment_status'),
        ('jobapp', '0033_user_login_time'),
    ]

    operations = [
    ]
