# Generated by Django 5.2 on 2026-08-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0033_companyprofile_tagline_companyannouncement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerplatformsettings',
            name='allow_multiple_company',
        ),
        migrations.AddField(
            model_name='employerplatformsettings',
            name='allow_jobseeker_contact_visibility',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='companyannouncement',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('expired', 'Expired')], default='draft', max_length=20),
        ),
    ]
