# Generated by Django 5.2 on 2026-08-19 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0033_companyprofile_company_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='authorization_contact',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='authorization_document',
            field=models.FileField(blank=True, null=True, upload_to='company/partner-authorizations/'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='partner_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='services_offered',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='companyverification',
            name='parent_approval_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='companyverification',
            name='parent_approval_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Hold', 'Hold'), ('Reject', 'Reject'), ('Verified', 'Verified')], db_index=True, default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='companyverification',
            name='parent_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyverification',
            name='parent_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_partner_verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postajob',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='jobapp.companyprofile'),
        ),
    ]
