# Generated by Django 5.2 on 2026-05-06 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0034_merge_20260504_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AJobSeeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='postajob',
            name='last_date_to_apply',
        ),
        migrations.AddField(
            model_name='postajob',
            name='flagged',
            field=models.BooleanField(default=False, help_text='Admin flagged for review'),
        ),
        migrations.AlterField(
            model_name='companyverification',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Hold', 'Hold'), ('Reject', 'Reject'), ('Verified', 'Verified')], db_index=True, default='Pending', max_length=10),
        ),
        migrations.CreateModel(
            name='AEmployer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.acompany')),
            ],
        ),
        migrations.CreateModel(
            name='AJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.acompany')),
            ],
        ),
        migrations.CreateModel(
            name='JobHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField()),
                ('job_title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField()),
                ('data', models.JSONField(default=dict)),
                ('employer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
