# Generated by Django 5.2 on 2026-08-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0034_remove_employerplatformsettings_allow_multiple_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerplatformsettings',
            name='allow_multiple_company',
            field=models.BooleanField(default=False),
        ),
    ]
