# Generated by Django 5.2 on 2026-05-11 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0035_acompany_ajobseeker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='jobapp.postajob'),
        ),
        migrations.AddField(
            model_name='plan',
            name='highlight_limit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postajob',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='postajob',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postajob',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postajob',
            name='highlighted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postajob',
            name='is_highlighted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('message', 'Message'), ('job_alert', 'Job Alert'), ('application', 'Application Update'), ('system', 'System Notification'), ('job_approved', 'Job Approved'), ('job_rejected', 'Job Rejected')], default='system', max_length=50),
        ),
    ]
