# Generated by Django 5.2 on 2026-09-10 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0035_employerplatformsettings_allow_multiple_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyannouncement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL),
        ),
    ]
