# Generated by Django 5.2 on 2026-09-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0036_companyannouncement_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_expired_notice_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='password_expiry_warning_sent',
            field=models.BooleanField(default=False),
        ),
    ]
