# Generated by Django 5.2 on 2026-09-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0037_user_password_expired_notice_sent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password_expired_notice_sent',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password_expiry_warning_sent',
        ),
        migrations.AddField(
            model_name='user',
            name='password_expired_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_warning_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
